# source everything

# work or home
ENV="WORK"

files=(
  ".aliases.zsh"
  ".beforeprompt.zsh"
  ".instantprompt.zsh"
  ".afterprompt.zsh"
  ".config.zsh"
  ".fzf.zsh"
  ".env.zsh"
  ".others.zsh"
)

for file in $files; do
  [ -f $HOME/$file ] && source $HOME/$file || echo "Failed to source $file"
done

# add home dir .bin to path
export PATH=$HOME/.bin:$PATH

# outputs todo from obsidian workplace
NOTE_PATH=$HOME/work/work_notes/TODO.md

if [[ -s $NOTE_PATH ]]; then

  # if lolcat exists and is executable
  if hash lolcat 2>/dev/null
  then
    echo TODO: | lolcat -t -F 0.85
  else
    echo TODO:
  fi
  if hash glow 2>/dev/null; then
    glow $NOTE_PATH
  fi
fi

# # THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
# export SDKMAN_DIR="$HOME/.sdkman"
# [[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"

eval "$(zoxide init zsh)"
# source ~/powerlevel10k/powerlevel10k.zsh-theme
# source /Users/danielvolchek/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
# export PATH="/opt/homebrew/Cellar/mysql-client@5.7/5.7.42/bin:$PATH"
# eval "$(pyenv init -)"
#
# export PATH="$HOME/.jenv/bin:$PATH"
# eval "$(jenv init -)"
#
# # The next line updates PATH for the Google Cloud SDK.
# if [ -f '/Users/danielvolchek/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/danielvolchek/google-cloud-sdk/path.zsh.inc'; fi
#
# # The next line enables shell command completion for gcloud.
# if [ -f '/Users/danielvolchek/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/danielvolchek/google-cloud-sdk/completion.zsh.inc'; fi
#
# # add mysql to path
# export PATH="$HOME/.krew/bin:$PATH"
# # kubectl auto-completion
# source <(kubectl completion zsh)
#
# export TESTCONTAINERS_RYUK_DISABLED=true
#
# bun completions
[ -s "/Users/danielvolchek/.bun/_bun" ] && source "/Users/danielvolchek/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

# android studio 
export ANDROID_HOME=/usr/local/share/android-sdk
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools

alias ll='ls -la'
